version: "3.8"

services:
  app:
    build: .
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chat
      SPRING_DATASOURCE_USERNAME: chat
      SPRING_DATASOURCE_PASSWORD: chat
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
