name: CI - ChatBot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: chat
          POSTGRES_PASSWORD: chat
          POSTGRES_DB: chat
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 7s
          --health-timeout 5s
          --health-retries 3

    env:
      DB_URL: jdbc:postgresql://localhost:5432/chat
      DB_USERNAME: chat
      DB_PASSWORD: chat
      PORT: 9090

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for Postgres to start
        run: |
          echo "Waiting for postgres..."
          until pg_isready -h localhost -p 5432; do sleep 2; done

      - name: Build and Test
        run: mvn clean install -Dspring.profiles.active=test
